projectName: Thought About You
projectUrl: http://thoughtaboutyou.net/
projectUrlReadable: thoughtaboutyou.net

paginate: 3

root: 
permalink: /:year/:month/:day/:title/

markdown: rdiscount
pygments: true
lsi: true

googleAnalyticsTrackingId: UA-44605644
googleAnalyticsTrackingDomain: thoughtaboutyou.net