projectName: Thought About You
projectUrl: https://thoughtaboutyou.net/
projectUrlReadable: thoughtaboutyou.net

gems: [
	jekyll-paginate
]
paginate: 3

root: 
permalink: /:year/:month/:day/:title/

highlighter: rouge
lsi: true

googleAnalyticsTrackingId: UA-44605644-1
googleAnalyticsTrackingDomain: thoughtaboutyou.net